config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :dashboard, only: [:index] do
    collection do
      get :user_list
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord

  def self.valid_user?(user)
    return { errors: 'Passwords must match' } unless check_password(user)
    user
  end

  def self.persist(user)
    Database.save(user)
  end

  def self.get(username)
    Database.get(username)
  end

  def self.list
    Database.user_list
  end

  private_class_method

  def self.check_password(user)
    user[:password] == user[:password_confirmation]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    @current_user ||= User.get(session[:username]) if session[:username]
  end

  helper_method :current_user

  def authorize
    redirect_to login_path(errors: ['Please log in']) unless current_user
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :authorize

  def index; end

  def user_list
    @user_list = User.list
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController

  def new; end

  def create
    user = User.get(params[:username])

    if user && PasswordHash.authenticate(params[:password], user['password_digest'], user['salt'])
      session[:username] = user['username']
      redirect_to dashboard_index_path
    else
      redirect_to login_path(errors: ['Username or Password is invalid'])
    end
  end

  def destroy
    session[:username] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController

  def new; end

  def create
    user = User.valid_user?(user_params)

    if user.key?(:errors)
      redirect_to signup_path(errors: user[:errors])
    else
      user = User.persist(user_params)
      session[:username] = user['username']
      redirect_to dashboard_index_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<h1>Hello <%= current_user['username'] %></h1>

app/views/dashboard/user_list.html.erb
<div>
  <p>Users List</p>
  <ul>
    <% @user_list.each do |user| %>
      <li><%= user %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FusionRLCodeChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      Signed in as <%= current_user['username'] %> |
      <%= link_to 'Dashboard', dashboard_index_path %> |
      <%= link_to 'User List', user_list_dashboard_index_path %> |
      <%= link_to 'Logout', logout_path %>
    <% else %>
      <%= link_to 'Login', login_path %> |
      <%= link_to 'Signup', signup_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Signup!</h1>
<% if params[:errors].present? %>
<ul>
  <li style="color: red;"><%= params[:errors] %></li>
</ul>
<% end %>

<%= form_for :user, url: users_path do |f| %>
  Username: <br> <%= f.text_field :username %> <br>
  Password: <br> <%= f.password_field :password %> <br>
  Password Confirmation: <br> <%= f.password_field :password_confirmation %> <br>
  <%= f.submit 'Submit'%>
<% end %>